--------------------------------------------------------
--  File created - Thursday-April-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PACJENT
--------------------------------------------------------

  CREATE TABLE "DKOLASKA"."PACJENT" 
   (	"ID_PACJENTA" NUMBER(6,0), 
	"PESEL" NUMBER(11,0), 
	"IMIE" VARCHAR2(100 BYTE), 
	"NAZWISKO" VARCHAR2(100 BYTE), 
	"DATA_URODZENIA" DATE, 
	"MIEJSCE_URODZENIA" VARCHAR2(100 BYTE), 
	"NAZWA_ODDZIALU_NFZ" VARCHAR2(100 BYTE), 
	"ID_LEKARZA_RODZINNEGO" NUMBER(8,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 COMPRESS FOR OLTP LOGGING
  TABLESPACE "II_DATA" ;
--------------------------------------------------------
--  DDL for Index PACJENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DKOLASKA"."PACJENT_PK" ON "DKOLASKA"."PACJENT" ("ID_PACJENTA", "PESEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "II_DATA" ;
--------------------------------------------------------
--  Constraints for Table PACJENT
--------------------------------------------------------

  ALTER TABLE "DKOLASKA"."PACJENT" ADD CONSTRAINT "PACJENT_PK" PRIMARY KEY ("ID_PACJENTA", "PESEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "II_DATA"  ENABLE;
 
  ALTER TABLE "DKOLASKA"."PACJENT" MODIFY ("ID_PACJENTA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."PACJENT" MODIFY ("PESEL" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."PACJENT" MODIFY ("IMIE" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."PACJENT" MODIFY ("NAZWISKO" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."PACJENT" MODIFY ("DATA_URODZENIA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."PACJENT" MODIFY ("MIEJSCE_URODZENIA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."PACJENT" MODIFY ("NAZWA_ODDZIALU_NFZ" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PACJENT
--------------------------------------------------------

  ALTER TABLE "DKOLASKA"."PACJENT" ADD CONSTRAINT "PACJENT_FK_LEKARZ" FOREIGN KEY ("ID_LEKARZA_RODZINNEGO")
	  REFERENCES "DKOLASKA"."LEKARZ" ("ID_LEKARZA") ENABLE;
 
  ALTER TABLE "DKOLASKA"."PACJENT" ADD CONSTRAINT "PACJENT_FK_ODDZIAL" FOREIGN KEY ("NAZWA_ODDZIALU_NFZ")
	  REFERENCES "DKOLASKA"."ODDZIAL_NFZ" ("NAZWA_ODDZIALU") ENABLE;
