--------------------------------------------------------
--  File created - Thursday-April-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECEPTA
--------------------------------------------------------

  CREATE TABLE "DKOLASKA"."RECEPTA" 
   (	"NUMER_RECEPTY" NUMBER(12,0), 
	"DATA_WYSTAWIENIA" DATE, 
	"TRESC" VARCHAR2(500 BYTE), 
	"PESEL_PACJENTA" NUMBER(11,0), 
	"ID_PACJENTA" NUMBER(6,0), 
	"ID_LEKARZA" NUMBER(8,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 COMPRESS FOR OLTP LOGGING
  TABLESPACE "II_DATA" ;
--------------------------------------------------------
--  DDL for Index RECEPTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DKOLASKA"."RECEPTA_PK" ON "DKOLASKA"."RECEPTA" ("NUMER_RECEPTY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "II_DATA" ;
--------------------------------------------------------
--  Constraints for Table RECEPTA
--------------------------------------------------------

  ALTER TABLE "DKOLASKA"."RECEPTA" ADD CONSTRAINT "RECEPTA_PK" PRIMARY KEY ("NUMER_RECEPTY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "II_DATA"  ENABLE;
 
  ALTER TABLE "DKOLASKA"."RECEPTA" MODIFY ("DATA_WYSTAWIENIA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."RECEPTA" MODIFY ("TRESC" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."RECEPTA" MODIFY ("NUMER_RECEPTY" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."RECEPTA" MODIFY ("PESEL_PACJENTA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."RECEPTA" MODIFY ("ID_PACJENTA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."RECEPTA" MODIFY ("ID_LEKARZA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table RECEPTA
--------------------------------------------------------

  ALTER TABLE "DKOLASKA"."RECEPTA" ADD CONSTRAINT "RECEPTA_FK_LEKARZ" FOREIGN KEY ("ID_LEKARZA")
	  REFERENCES "DKOLASKA"."LEKARZ" ("ID_LEKARZA") ENABLE;
 
  ALTER TABLE "DKOLASKA"."RECEPTA" ADD CONSTRAINT "RECEPTA_FK_PACJENT" FOREIGN KEY ("ID_PACJENTA", "PESEL_PACJENTA")
	  REFERENCES "DKOLASKA"."PACJENT" ("ID_PACJENTA", "PESEL") ENABLE;
