--------------------------------------------------------
--  File created - Thursday-April-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SKIEROWANIE
--------------------------------------------------------

  CREATE TABLE "DKOLASKA"."SKIEROWANIE" 
   (	"ID_SKIEROWANIA" NUMBER, 
	"TRESC" VARCHAR2(500 BYTE), 
	"DATA_WYSTAWIENIA" DATE, 
	"PODPIS_WYPISUJACEGO" BLOB, 
	"ID_LEKARZA" NUMBER(8,0), 
	"ID_PACJENTA" NUMBER(6,0), 
	"PESEL_PACJENTA" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 COMPRESS FOR OLTP LOGGING
  TABLESPACE "II_DATA" 
 LOB ("PODPIS_WYPISUJACEGO") STORE AS BASICFILE (
  TABLESPACE "II_DATA" ENABLE STORAGE IN ROW CHUNK 2048 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Index SKIEROWANIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DKOLASKA"."SKIEROWANIE_PK" ON "DKOLASKA"."SKIEROWANIE" ("ID_SKIEROWANIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "II_DATA" ;
--------------------------------------------------------
--  Constraints for Table SKIEROWANIE
--------------------------------------------------------

  ALTER TABLE "DKOLASKA"."SKIEROWANIE" ADD CONSTRAINT "SKIEROWANIE_PK" PRIMARY KEY ("ID_SKIEROWANIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "II_DATA"  ENABLE;
 
  ALTER TABLE "DKOLASKA"."SKIEROWANIE" MODIFY ("ID_SKIEROWANIA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SKIEROWANIE" MODIFY ("TRESC" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SKIEROWANIE" MODIFY ("DATA_WYSTAWIENIA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SKIEROWANIE" MODIFY ("PODPIS_WYPISUJACEGO" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SKIEROWANIE" MODIFY ("ID_LEKARZA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SKIEROWANIE" MODIFY ("ID_PACJENTA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SKIEROWANIE" MODIFY ("PESEL_PACJENTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SKIEROWANIE
--------------------------------------------------------

  ALTER TABLE "DKOLASKA"."SKIEROWANIE" ADD CONSTRAINT "SKIEROWANIE_FK_LEKARZ" FOREIGN KEY ("ID_LEKARZA")
	  REFERENCES "DKOLASKA"."LEKARZ" ("ID_LEKARZA") ENABLE;
 
  ALTER TABLE "DKOLASKA"."SKIEROWANIE" ADD CONSTRAINT "SKIEROWANIE_FK_PACJENT" FOREIGN KEY ("ID_PACJENTA", "PESEL_PACJENTA")
	  REFERENCES "DKOLASKA"."PACJENT" ("ID_PACJENTA", "PESEL") ENABLE;
