--------------------------------------------------------
--  File created - Thursday-April-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SZCZEPIENIE
--------------------------------------------------------

  CREATE TABLE "DKOLASKA"."SZCZEPIENIE" 
   (	"ID_SZCZEPIENIA" NUMBER(12,0), 
	"NAZWA_CHOROBY" VARCHAR2(100 BYTE), 
	"DATA_SZCZEPIENIA" DATE, 
	"ID_PACJENTA" NUMBER(6,0), 
	"PESEL_PACJENTA" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 COMPRESS FOR OLTP LOGGING
  TABLESPACE "II_DATA" ;
--------------------------------------------------------
--  DDL for Index SZCZEPIENIE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DKOLASKA"."SZCZEPIENIE_PK" ON "DKOLASKA"."SZCZEPIENIE" ("ID_SZCZEPIENIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "II_DATA" ;
--------------------------------------------------------
--  Constraints for Table SZCZEPIENIE
--------------------------------------------------------

  ALTER TABLE "DKOLASKA"."SZCZEPIENIE" MODIFY ("ID_SZCZEPIENIA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SZCZEPIENIE" MODIFY ("NAZWA_CHOROBY" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SZCZEPIENIE" MODIFY ("DATA_SZCZEPIENIA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SZCZEPIENIE" MODIFY ("ID_PACJENTA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SZCZEPIENIE" MODIFY ("PESEL_PACJENTA" NOT NULL ENABLE);
 
  ALTER TABLE "DKOLASKA"."SZCZEPIENIE" ADD CONSTRAINT "SZCZEPIENIE_PK" PRIMARY KEY ("ID_SZCZEPIENIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "II_DATA"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SZCZEPIENIE
--------------------------------------------------------

  ALTER TABLE "DKOLASKA"."SZCZEPIENIE" ADD CONSTRAINT "SZCZEPIENIE_FK1" FOREIGN KEY ("ID_PACJENTA", "PESEL_PACJENTA")
	  REFERENCES "DKOLASKA"."PACJENT" ("ID_PACJENTA", "PESEL") ENABLE;
