CREATE INDEX TEST1_IDX1_LICZBA20 ON TEST1(LICZBA20);

EXPLAIN PLAN SET STATEMENT_ID = 'ST_AFTER' FOR 
SELECT /*+ NO_INDEX(TEST1 TEST1_IDX1_LICZBA20) */ * 
FROM TEST1
WHERE TEST1.LICZBA20=3;

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());

EXPLAIN PLAN SET STATEMENT_ID = 'ST_AFTER' FOR 
SELECT /*+ INDEX(TEST1 TEST1_IDX1_LICZBA20) */ * 
FROM TEST1
WHERE TEST1.LICZBA20=3;

SELECT PLAN_TABLE_OUTPUT FROM TABLE(DBMS_XPLAN.DISPLAY());

DROP INDEX "DKOLASKA"."TEST1_IDX1_LICZBA20";