version: '3'
services:
  backend:
    depends_on:
      - db
    build: .
    ports:
      - '5000:80'
    tmpfs:
      - /tmp
    environment:
      - DB_USERNAME=${MARIADB_USERNAME}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - DB_DATABASE=${MARIADB_DATABASE}
      - DB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  initializer:
    depends_on:
      - db
    build: initializer
    tmpfs:
      - /tmp
    environment:
      - DB_USERNAME=${MARIADB_USERNAME}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - DB_DATABASE=${MARIADB_DATABASE}
      - DB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  db:
    image: webhippie/mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USERNAME=${MARIADB_USERNAME}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    volumes:
      - "./data/mysql:/var/lib/mysql:rw"
      - "./data/backup:/var/lib/backup:rw"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '5010:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
  db-face:
    image: dbface/dbface-docker
    depends_on:
      - db
    ports:
      - '5020:80'
    volumes:
      - './dbface:/var/www/user'
